/* Copyright 2026 Ada Logics Ltd
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
 * libFuzzer harness for wolfSSH server-side packet processing.
 *
 * The harness drives wolfSSH_accept() as if it were running a server.
 * The fuzzer-provided bytes are exposed to wolfSSH through a custom
 * IO recv callback, simulating untrusted data arriving from a network
 * client. Send bytes from the server are discarded. This exercises
 * the SSH wire-format parser, version exchange, kex, and authentication
 * paths -- the primary attack surface for an SSH server.
 */
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include <wolfssh/ssh.h>
#include <wolfssh/error.h>

#include "server_key_rsa.h" /* generated by build.sh: server_key_rsa_der */

typedef struct {
    const uint8_t* data;
    size_t size;
    size_t pos;
} FuzzIO;

static int FuzzRecv(WOLFSSH* ssh, void* buf, word32 sz, void* vctx) {
    (void)ssh;
    FuzzIO* io = (FuzzIO*)vctx;
    if (io->pos >= io->size) {
        return WS_CBIO_ERR_CONN_CLOSE;
    }
    size_t remaining = io->size - io->pos;
    if (sz > remaining) sz = (word32)remaining;
    memcpy(buf, io->data + io->pos, sz);
    io->pos += sz;
    return (int)sz;
}

static int FuzzSend(WOLFSSH* ssh, void* buf, word32 sz, void* vctx) {
    (void)ssh; (void)buf; (void)vctx;
    /* Pretend we wrote everything. */
    return (int)sz;
}

static int FuzzUserAuth(byte authType, WS_UserAuthData* authData, void* ctx) {
    (void)authType; (void)authData; (void)ctx;
    return WOLFSSH_USERAUTH_SUCCESS;
}

static int initialized = 0;

int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
    if (size == 0 || size > (1 << 17)) return 0;

    if (!initialized) {
        if (wolfSSH_Init() != WS_SUCCESS) return 0;
        initialized = 1;
    }

    WOLFSSH_CTX* ctx = wolfSSH_CTX_new(WOLFSSH_ENDPOINT_SERVER, NULL);
    if (ctx == NULL) return 0;

    if (wolfSSH_CTX_UsePrivateKey_buffer(ctx,
            server_key_rsa_der, server_key_rsa_der_len,
            WOLFSSH_FORMAT_ASN1) != WS_SUCCESS) {
        wolfSSH_CTX_free(ctx);
        return 0;
    }

    wolfSSH_SetIORecv(ctx, FuzzRecv);
    wolfSSH_SetIOSend(ctx, FuzzSend);
    wolfSSH_SetUserAuth(ctx, FuzzUserAuth);

    WOLFSSH* ssh = wolfSSH_new(ctx);
    if (ssh == NULL) {
        wolfSSH_CTX_free(ctx);
        return 0;
    }

    FuzzIO io = { data, size, 0 };
    wolfSSH_SetIOReadCtx(ssh, &io);
    wolfSSH_SetIOWriteCtx(ssh, &io);

    /* Drive the SSH state machine. Ignore the return value -- we only
     * care about memory-safety issues surfaced by the sanitizers. */
    (void)wolfSSH_accept(ssh);

    wolfSSH_free(ssh);
    wolfSSH_CTX_free(ctx);
    return 0;
}
